# Constants the original's tuning table does NOT hold: geometry, and the bridge
# between the table's "frames" and wall-clock time.
#
# Anything that IS in VALUELST.RES belongs in the generated values.gd instead,
# addressed by the original's own resource number. Duplicating a value here
# would create two sources of truth, and the wrong one would win eventually.
#
# The Res class below names those resource numbers without copying their values,
# so callers read Values.V[Const.Res.FUZE_FRAMES] rather than Values.V[41].
#
# See docs/ORACLE.md for what each resource number means.
class_name Const

# values.gd is GENERATED by tools/valuelist.py and gitignored. verify.sh builds
# it as its first step, so a fresh clone regenerates rather than fails to parse.
const Values := preload("res://scripts/core/values.gd")

## Playfield in tiles. Fixed by the scheme file format: 11 rows of 15.
const FIELD_W := 15
const FIELD_H := 11

## Tile size in pixels. These are NOT square, which is why the original's
## movement is anisotropic in tile terms — it moves in pixels, so the same
## speed crosses a row faster than a column. ORACLE row 2.
const BLOCK_W := 40
const BLOCK_H := 36

## Where the playfield's top-left corner sits inside the screen.
##
## DERIVED, because the original derives them. `BM95.EXE` sets the whole field
## geometry in one function at 0x42647A — which names its own source file,
## `map.c`, line 317 — and it reads:
##
##     FIELD_W  = 15 ; FIELD_H = 11 ; BLOCK_W = 40 ; BLOCK_H = 36
##     X_ORIGIN = (screen_w - FIELD_W * BLOCK_W) / 2
##     Y_ORIGIN = screen_h - FIELD_H * BLOCK_H - 16
##
## So the field is CENTRED horizontally and pinned 16 px off the bottom, and
## everything above it is the status area. At 640x480 that is 20 and **68**.
##
## The port had 66 for the Y offset, so every tile, bomb, flame, powerup and
## player was drawn two pixels high. docs/BUGS.md D24.
const FIELD_X_OFF := (SCREEN_W - FIELD_W * BLOCK_W) / 2
const FIELD_Y_OFF := SCREEN_H - FIELD_H * BLOCK_H - BOTTOM_MARGIN

## The 16 in map.c's Y_ORIGIN. Named rather than inline because it is the only
## number in that expression that is not derived from something else.
const BOTTOM_MARGIN := 16

## The status area above the playfield, in pixels. Whatever the field does not
## use: 68 at 640x480. The level backgrounds leave it plain, so the readout is
## drawn over them.
const STATUS_H := FIELD_Y_OFF

## How much of that area the READOUT may use, and how far down an actor sprite
## may reach.
##
## MEASURED from the eleven level backgrounds, which agree: ten of them are
## solid black from y=0 to y=41 across the whole width of the playfield, and
## FIELD1.PCX — the one exception — is solid grey over exactly the same rows
## before its border tiles begin. Below 42 every background draws its own
## frame, and above it none of them draws anything. So 42 is where the art
## says the panel ends.
##
## The rest of the status area, 42 to 67, is border art, and a sprite is
## ALLOWED into it: a standing bomberman is 67 px of ink over a 36 px cell, so
## one on the top row needs 30 px above the playfield or its head is cut off.
## It gets 26 of them and is clipped at the panel, which is the same line the
## background changes on — so the cut reads as the frame rather than as a
## broken sprite, and nothing ever crosses the clock. docs/BUGS.md D28.
const HUD_H := 42

## The original's own resolution, and what its PCX backgrounds are authored at.
## Which team a slot belongs to when the scheme does not say.
##
## SLOTS 1-5 AGAINST 6-10, not odd against even. OPTIONS.BM says so twice, in
## its own words: "Generally, players 1 through 5 are on one team and players 6
## through 10 are on another", and again under Wally Bomb — "To ensure that the
## teams are placed properly, player slots 1 through 5 are on one team and
## player slots 6 through 10 are on the other."
##
## The port used `slot % 2` until that file arrived, which puts every player on
## the opposite team from the original and makes a team scheme's start
## positions — which are laid out for the halves — pair the wrong people.
## docs/BUGS.md D20.
##
## A scheme's own -S line still wins where it states a team; this is only the
## fallback for the 31 of 67 schemes that do not.
static func default_team(slot: int) -> int:
	return 0 if slot < PLAYER_COUNT / 2 else 1


const SCREEN_W := 640
const SCREEN_H := 480

## Simulation rate. VALUELST resource 30 is the frame rate the game attempts
## and resource 25 is the nominal rate every frame-count value in the file is
## expressed against; both are 20. So one tick is 50 ms, and a "frames" value
## from the table is a tick count with no conversion needed.
##
## Deliberately a constant rather than a read of resource 30: the sim rate is
## structural, and a data file must not be able to change it out from under the
## tests. test_values.gd asserts the two agree.
const TICK_HZ := 20
const TICK_MS := 50

const POWERUP_COUNT := 13
const PLAYER_COUNT := 10
## Twelve diseases exist (Types.Disease, named from SOUNDLST.RES) but VALUELST
## only holds NINE duration slots for them. Both numbers are real and they are
## not the same number — docs/BUGS.md Q1.
const DISEASE_COUNT := 12
const DISEASE_DURATION_SLOTS := 9


## VALUELST resource numbers. The numbers are the original's; only these names
## are ours. Grouped by what they govern.
class Res:
	## Timing and rate
	const FLAME_ANIM_FRAMES := 10       ## flame animation length
	const BRICK_ANIM_FRAMES := 20       ## brick disintegration length
	const NOMINAL_FPS := 25             ## reference rate for every frame count
	const TARGET_FPS := 30              ## rate the game attempts
	const MAX_ADVANCE_MS := 31          ## clamp on one frame's advance
	const SCREEN_MIN_SECONDS := 13      ## minimum wait at a screen, for net play
	const TEAM_COLOUR_FRAMES := 32      ## true colours before team colours
	const LEVEL_COUNT := 35             ## how many levels are defined
	const RANDOM_START := 40            ## default for randomised start cells

	## Campaign mode — the three .CAM files' own numbers. 1200 and 1205 are
	## 1-in-N chances, per VALUELST's header rule; 1300/1310/1320 are points,
	## each comment ending "(in campaign mode only)".
	const CREATURE_TURN_CHANCE := 1200  ## 1-in-N to turn at an intersection
	const CREATURE_AWAY_CHANCE := 1205  ## 1-in-N that the turn is NOT toward a human
	const SCORE_AI := 1300              ## 250 for killing an AI
	const SCORE_ROVER := 1310           ## 15 for a rover
	const SCORE_GHOST := 1320           ## 25 for a ghost
	const FUZE_FRAMES := 41             ## bomb fuze
	const START_SPEED := 42             ## hundredths of a px/frame
	const DEFAULT_BOMBTYPE := 43        ## 0 regular, 1 trigger, 2 jelly

	## Starting loadout, 50..64, indexed by Types.PowerUp
	const BORN_WITH_BASE := 50
	## Accumulation caps, 550..564, indexed by Types.PowerUp. 0 means no limit.
	const CAP_BASE := 550
	## Per-level powerup counts, 400..412, indexed by Types.PowerUp.
	## A negative value means that many 1-in-10 rolls rather than a count.
	const SPAWN_BASE := 400

	## Speed deltas — additive, not multiplicative. ORACLE row 3.
	const SKATE_BONUS := 90
	const CLOG_PENALTY := 91

	## Round structure
	const ROUND_SECONDS := 100          ## default length
	const HURRY_AT_SECONDS := 101       ## time remaining when Hurry starts
	const OVERPOWER_LOCKOUT := 102      ## window where strong powers won't drop
	const WINS_TO_WIN := 310

	# --- the Goldman roulette, whose whole animation is in the data.
	# These entries are MULTI-VALUE: 1000 is "320,240" and 1002 is "200,150",
	# so Values.V[1000] is an array. tools/valuelist.py has always parsed
	# those; 40 of the 251 resources are arrays.
	const ROULETTE_CENTRE := 1000        ## x, y — "center of roulette wheel"
	const ROULETTE_RADII := 1002         ## x, y — "radius(es) of perimeter"
	const ROULETTE_RESOLUTION := 1004    ## "resolution of the circle"
	const ROULETTE_LISSAJOUS := 1006     ## "X,Y parameters for lissajous"
	const GOLDMAN_TWINKLE_SECONDS := 1010

	# --- screen text positions, as (x, y, line pitch, width). 700..815 is
	# every screen the original draws in code, which is why the roulette is
	# the one screen this port did not have to lay out itself.
	const POS_MATCH_WINNER := 800        ## "player %u wins the match..."
	const POS_ROULETTE_TITLE := 805      ## "Goldman Roulette Wheel"
	const POS_PRESS_F1 := 790            ## "Press F1 for help"
	const ENCLOSE_DEPTH := 27            ## 0 none, 1 two rows, 2 four rows, 3 all
	const ENCLOSE_DEPTH_COUNT := 28
	const WALL_DETONATES_BOMB := 46     ## 0 destroy, 1 detonate

	## Diseases
	const DISEASE_DESTROYABLE := 120
	const DISEASE_TIME_LIMITED := 121
	const DISEASE_RECYCLES := 122
	const DISEASE_MULTIPLIES := 123
	const DISEASE_CURABLE := 124
	const DISEASE_CURE_CHANCE := 125    ## 1-in-N on picking up a powerup
	const DISEASE_FRESHNESS := 129      ## frames before it can pass again
	const DISEASE_DURATION_BASE := 130  ## 130..138, one per disease

	## Conveyors, 190..192
	const CONVEYOR_SPEED_COUNT := 189
	const CONVEYOR_SPEED_BASE := 190

	## Bombs
	const KICKED_BOMB_SPEED := 300
	const PUNCHED_BOMB_SPEED := 301
	const DUD_MIN_SECONDS := 320
	const DUD_RAND_SECONDS := 321
	const DUD_CHANCE := 322             ## 1-in-N
	const DUD_WAIT_FRAMES := 323
	const DUD_WAIT_RAND_FRAMES := 324
	const PUNCH_ARC_BIG := 660          ## initial three-space bounce height
	const PUNCH_ARC_SMALL := 661        ## subsequent one-space bounces
	const PICKUP_PAUSE_FRAMES := 665
	const JELLY_TURN_CHANCE := 667      ## 1-in-N at each intersection
	const PICKUP_CURVE_BASE := 500      ## 500,502,504,506 — four (x,y) points

	## Players
	const DEATH_ANIM_COUNT := 105
	const CORNER_ANIM_COUNT := 330
	const HEAD_HIT_MIN_LOSS := 670
	const HEAD_HIT_RAND_LOSS := 671
	const TRAMP_BOUNCE_FRAMES := 680
	const TRAMP_RISE_PX := 681
	const START_POS_BASE := 600         ## 600..618, two apart, one (x,y) each
	const COLOUR_BASE := 200            ## 200..247, three apart, one RGB each

	## Level features
	const REGEN_INTERVAL_BASE := 340    ## 340..350, seconds; 0 = no regeneration
	const REGEN_CLEAR_RADIUS := 695
	const ICE_DELAY_BASE := 450         ## 450..460, milliseconds
	const RANDOM_LEVEL_ENABLED_BASE := 1150  ## 1150..1161

	## Flavour
	const ATTRACT_SECONDS := 92         ## under 5 disables attract mode
	const TAUNT_CHANCE := 95            ## 1-in-N
	const CONCURRENT_SOUNDS := 8

	## AI
	const AI_PERSONALITIES := 900
	const AI_FIREGOD_LOOKAHEAD := 910
	const AI_BLAST_BRICKS_CHANCE := 915 ## 1-in-N
	const AI_POWERUP_RADIUS := 920

	## How many `cornerhead N` sequences CORNER0-7 hold between them — 13, per
	## docs/BUGS.md Q3. `0x41F29B` (`player_update`) reads it to pick which one
	## plays when a player is boxed in on all four sides.
	const CORNERHEAD_COUNT := 330


## Convert a VALUELST speed — hundredths of a pixel per frame — to pixels per
## tick. A tick IS a frame, so this is only a divide by 100.
static func speed_px_per_tick(hundredths: int) -> float:
	return hundredths / 100.0


## The same speed in tiles per second, horizontally. Useful for reading numbers
## off against other implementations; the sim itself works in pixels.
static func speed_tiles_h(hundredths: int) -> float:
	return hundredths / 100.0 * TICK_HZ / float(BLOCK_W)


## And vertically. Differs from the horizontal figure because tiles are 40x36,
## which is the whole of ORACLE row 2.
static func speed_tiles_v(hundredths: int) -> float:
	return hundredths / 100.0 * TICK_HZ / float(BLOCK_H)


## Frames from the tuning table to milliseconds.
static func frames_to_ms(frames: int) -> int:
	return frames * TICK_MS


## Top-left pixel of a tile, in screen space.
static func tile_origin(tx: int, ty: int) -> Vector2i:
	return Vector2i(FIELD_X_OFF + tx * BLOCK_W, FIELD_Y_OFF + ty * BLOCK_H)


## How far below an actor's stored position its sprite anchor sits.
##
## `BLOCK_H / 2 - 1`, and that is not a guess. Two facts pin it:
##
##   * Every sprite hotspot on the disc is BOTTOM-CENTRE with all of the ink
##     above it — measured: a standing bomberman is 35x67 with its hotspot one
##     pixel below its lowest ink, and the bomb, flame and shadow frames have
##     their hotspot exactly on their bottom edge.
##   * An actor's stored y is its cell CENTRE. `BM95.EXE`'s `tile_y` (0x4266A3)
##     recovers the row as `(py - Y_ORIGIN - (BLOCK_H/2 - 1)) / BLOCK_H`, so
##     the same 17 that converts a position to a row converts it to the bottom
##     of that row.
##
## So the hotspot belongs on the cell's bottom edge, and the sprite grows
## upward from it.
const ANCHOR_DROP := BLOCK_H / 2 - 1


## Where to put a sprite's hotspot, given an actor's position in FIELD-LOCAL
## pixels.
##
## The field origin is part of it because the simulation's coordinates are
## relative to the playfield, not to the screen. Bombs and flames were drawn
## without it — 20 px left and 68 px up — which is docs/BUGS.md D24.
static func actor_anchor(field_local: Vector2) -> Vector2:
	return Vector2(FIELD_X_OFF, FIELD_Y_OFF + ANCHOR_DROP) + field_local


## The playfield rectangle on screen. Actor drawing is clipped to it, so a
## sprite on the top row cannot hang off the top of the display: a bomberman is
## 67 px of ink over a 36 px cell, so it overlaps the row above by design and
## the status area by accident.
static func field_rect() -> Rect2:
	return Rect2(FIELD_X_OFF, FIELD_Y_OFF, FIELD_W * BLOCK_W,
		FIELD_H * BLOCK_H)


## The ten player colours, as VALUELST resources 200..247 give them: one RGB
## triple per .RMP file, three consecutive resources apart, five apart between
## colours. Components are 0..100, which is the range the recolour transform in
## scripts/render/recolour.gdshader expects, so they are returned unscaled.
##
##   0 white  1 black  2 red     3 blue    4 green
##   5 yellow 6 cyan   7 magenta 8 orange  9 purple
##
## Read from the table rather than transcribed. fpc_atomic's PlayerColors array
## agrees with all ten, which is one of the places it got the original right.
static func player_colour(index: int) -> Vector3i:
	var base := Res.COLOUR_BASE + index * 5
	return Vector3i(Values.V[base], Values.V[base + 1], Values.V[base + 2])


## The same colour normalised to 0..1, for a shader uniform or a modulate.
static func player_colour_f(index: int) -> Color:
	var c := player_colour(index)
	return Color(c.x / 100.0, c.y / 100.0, c.z / 100.0)


## Encode a player slot into a draw call's modulate for the recolour shader.
## See scripts/render/recolour.gdshader on why the slot travels in the alpha
## channel and not in the colour.
const TINT_CODES := 16
const TINT_NONE := 15


static func tint_modulate(slot: int) -> Color:
	var code: int = slot if (slot >= 0 and slot < PLAYER_COUNT) else TINT_NONE
	return Color(1.0, 1.0, 1.0, (code + 0.5) / float(TINT_CODES))


## The ten colours as the shader wants them.
static func palette() -> PackedVector3Array:
	var out := PackedVector3Array()
	for i in PLAYER_COUNT:
		var c := player_colour(i)
		out.append(Vector3(c.x / 100.0, c.y / 100.0, c.z / 100.0))
	return out


## Resolve a coordinate the way the original's data files do: a negative value
## wraps from the right or bottom edge. Documented on resource 600 and used by
## both the start positions and the EXTRA files.
static func wrap_x(x: int) -> int:
	return x + FIELD_W if x < 0 else x


static func wrap_y(y: int) -> int:
	return y + FIELD_H if y < 0 else y
